#!/bin/ksh -p
# SPDX-License-Identifier: CDDL-1.0

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2026 CompEd Software Design srl.
#

. $STF_SUITE/tests/functional/rsend/rsend.kshlib
. $STF_SUITE/include/math.shlib

#
# Description:
# Verify that the resume token generated by both zfs recv and zstream
# token -g includes a correct stream byte offset in the nvlist, and
# that zstream resume can use it to fast-forward to the resume point.
#
# Strategy:
# 1. Create a source dataset with data spanning multiple records.
# 2. Generate a full send stream, save to a cache file.
# 3. Interrupt a receive at a known byte position using dd to
#    produce a resume token.
# 4. Verify the token uses the standard 3-dash format.
# 5. Decode the token and verify it contains a non-zero stream_offset
#    in the nvlist.
# 6. Verify stream_offset points to a valid DRR record (drr_type 1-10).
# 7. Use zstream resume with the token to complete the receive;
#    success implicitly validates that the offset is correct.
# 8. Verify data integrity after the receive completes.
# 9. Also verify that zstream token -g produces a token with the
#    same object/offset as the kernel-generated token.
# 10. Repeat at multiple cut points.
#

verify_runnable "both"

log_assert "Verify resume token contains a correct stream byte offset."
log_onexit cleanup_pool $POOL2

typeset sendfs=$POOL2/fs
typeset recvfs=$POOL2/recv
typeset stream=$BACKDIR/cached.zfs

log_must zfs create -o compress=lz4 $sendfs
typeset dir=$(get_prop mountpoint $sendfs)

# Create data: full records (2MB) and embedded records (16KB)
truncate -s 2m $dir/full_records
log_must dd if=/dev/urandom of=$dir/full_records conv=notrunc bs=128k count=4
recsize=16384
log_must truncate -s $recsize $dir/embedded_records
log_must dd if=/dev/urandom of=$dir/embedded_records \
    seek=$((recsize - 8)) bs=1 count=8 conv=notrunc
log_must zfs snapshot $sendfs@snap1

# Generate cached full send stream
log_must eval "zfs send $sendfs@snap1 > $stream"

#
# Extract a uint64 field from the token's decoded nvlist output.
#
function get_token_field
{
	typeset token=$1
	typeset field=$2
	zstream token "$token" | awk -v field="$field" \
	    '$1 == field ":" { print $2 }'
}

#
# Verify the token format and offset at a given cut point (in bytes).
#
function test_cut_point
{
	typeset cut=$1
	typeset label=$2

	log_note "--- Testing cut at ${label} (${cut} bytes) ---"

	# Destroy recvfs for fresh receive
	zfs destroy -r $recvfs 2>/dev/null

	# Interrupted receive: do NOT pre-create the dataset; zfs receive -s
	# will create it and save resume state on interruption.
	zfs send $sendfs@snap1 | head -c $cut | zfs receive -s $recvfs
	typeset TOKEN
	TOKEN=$(zfs get -H -o value receive_resume_token $recvfs)
	if [[ -z "$TOKEN" || "$TOKEN" == "-" ]]; then
		log_fail "Failed to obtain resume token at cut $label"
	fi

	# Verify standard 3-dash format on the kernel token
	typeset dashes
	dashes=$(echo "$TOKEN" | tr -cd '-' | wc -c)
	if [[ "$dashes" -ne 3 ]]; then
		log_fail \
		    "Expected 3-dash token format at cut $label, got $dashes"
	fi

	typeset token_obj=$(get_token_field "$TOKEN" "object")
	typeset kern_soff=$(get_token_field "$TOKEN" "stream_offset")

	# Verify kernel token contains a non-zero stream_offset
	if [[ -z "$kern_soff" || "$kern_soff" -le 0 ]]; then
		log_fail "Kernel token stream_offset is missing or zero " \
		    "at $label: $kern_soff"
	fi
	log_note "Kernel token: object=$token_obj stream_offset=$kern_soff"

	#
	# Generate a token from the cut stream file using zstream token -g
	# and verify it has:
	#  - same object/offset as the kernel-generated token
	#  - a valid non-zero stream_offset
	#
	typeset cut_stream=$BACKDIR/cut_${label}.zfs
	head -c $cut < $stream > $cut_stream
	typeset GEN_TOKEN
	GEN_TOKEN=$(zstream token -g -i $cut_stream)
	if [[ -z "$GEN_TOKEN" ]]; then
		log_fail "zstream token -g failed at $label"
	fi

	typeset gen_obj=$(get_token_field "$GEN_TOKEN" "object")
	typeset gen_off=$(get_token_field "$GEN_TOKEN" "offset")
	typeset gen_soff=$(get_token_field "$GEN_TOKEN" "stream_offset")
	typeset kern_off=$(get_token_field "$TOKEN" "offset")

	if [[ "$gen_obj" != "$token_obj" ]]; then
		log_fail "Generated token object=$gen_obj differs from " \
		    "kernel token object=$token_obj at $label"
	fi
	if [[ "$gen_off" != "$kern_off" ]]; then
		log_fail "Generated token offset=$gen_off differs from " \
		    "kernel token offset=$kern_off at $label"
	fi

	# Verify stream_offset in generated token
	if [[ -z "$gen_soff" || "$gen_soff" -le 0 ]]; then
		log_fail "Generated token stream_offset is missing " \
		    "or zero at $label: $gen_soff"
	fi

	# Verify stream_offset is within the stream file
	typeset stream_size
	stream_size=$(stat -c %s "$stream" 2>/dev/null || \
	    stat -f %z "$stream" 2>/dev/null)
	if [[ "$gen_soff" -gt "$stream_size" ]]; then
		log_fail "stream_offset $gen_soff exceeds stream size " \
		    "$stream_size at $label"
	fi

	# Verify the record at stream_offset is a valid DRR record
	typeset drr_type=$(head -c $((gen_soff + 4)) $stream 2>/dev/null | \
	    tail -c 4 | od -A n -t u4 2>/dev/null | tr -d ' ')
	if [[ -n "$drr_type" ]]; then
		if [[ "$drr_type" -lt 1 || "$drr_type" -gt 10 ]]; then
			log_fail "Invalid drr_type=$drr_type at " \
			    "stream_offset $gen_soff ($label)."
		fi
		log_note "drr_type at stream_offset=$gen_soff = $drr_type"
	fi

	log_note "zstream token -g: object=$gen_obj, offset=$gen_off, " \
	    "stream_offset=$gen_soff"

	# Complete the receive using zstream resume
	typeset resume_stream=$BACKDIR/resume_${label}.zfs
	log_must eval "zstream resume -t '$TOKEN' -i $stream > $resume_stream"
	log_must eval "zfs receive -s $recvfs < $resume_stream"

	# Verify resume token cleared
	typeset post_token
	post_token=$(zfs get -H -o value receive_resume_token $recvfs)
	if [[ "$post_token" != "-" ]]; then
		log_fail \
		    "Resume token still present after completed receive at $label"
	fi

	# Verify snapshot exists
	zfs get -H -o value type $recvfs@snap1 > /dev/null 2>&1 ||
	    log_fail "Snapshot not found after resume at $label"

	# Verify data integrity
	diff -r $dir /$recvfs > /dev/null 2>&1 ||
	    log_fail "Data mismatch after resume receive at $label"

	log_note "PASS: cut at $label"
}

#
# Test multiple cut points to verify offset correctness at various
# positions within the stream.
#
typeset cut_points=(
	"4096"     # just past DRR_BEGIN
	"16384"    # mid metadata records
	"65536"    # within first data records
	"131072"   # ~128KB
	"524288"   # ~512KB
)

for cut_bytes in "${cut_points[@]}"; do
	test_cut_point $cut_bytes $cut_bytes
done

log_pass "Resume token contains correct stream byte offset."
